apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*.yaml
build:
  local:
    push: false
  artifacts:
    - image: graj9211/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dst: .
    - image: graj9211/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dst: .
    - image: graj9211/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dst: .
    - image: graj9211/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dst: .
    - image: graj9211/post
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dst: .
    - image: graj9211/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dst: .
